# baseURL = 'https://krishofer.com'
theme = "paper"
languageCode = 'en-AU'
title = 'Kris Hofer'
[params]
  # color style
  color = 'light' # linen, wheat, gray, light

  # header social icons
  twitter = 'krishofer'
  github = 'krishofer'
  rss = true

  # home page profile
  avatar = 'krishofer999@gmail.com'
  name = 'Kris Hofer'
  bio = 'Short spiel goes here.'

  # misc
  disableHLJS = true
  monoDarkIcon = true

  [menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now"
    weight = 2
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3